### ISSUE TITLE
Error while Loading Penpals

### ISSUE THREAD

**Issue by dannydenis14** [PastaSource/Slowly_Letter_Downloader#38]
```
INFO:__main__:Starting selenium
CRITICAL:__main__:There is no such driver by url https://chromedriver.storage.googleapis.com/129.0.6668/chromedriver_win32.zip
Traceback (most recent call last):
  File "main.py", line 1037, in open_chrome
  File "C:\Users\aaron\PycharmProjects\slowly scraper\venv\lib\site-packages\webdriver_manager\chrome.py", line 39, in install
  File "C:\Users\aaron\PycharmProjects\slowly scraper\venv\lib\site-packages\webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "C:\Users\aaron\PycharmProjects\slowly scraper\venv\lib\site-packages\webdriver_manager\core\download_manager.py", line 28, in download_file
  File "C:\Users\aaron\PycharmProjects\slowly scraper\venv\lib\site-packages\webdriver_manager\core\http.py", line 33, in get
  File "C:\Users\aaron\PycharmProjects\slowly scraper\venv\lib\site-packages\webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/129.0.6668/chromedriver_win32.zip
DEBUG:__main__:Iniating shutdown sequence
DEBUG:__main__:cef WindowInfo: <class 'cefpython_py39.WindowInfo'>
DEBUG:__main__:Shutting down cefpython
INFO:__main__:Program exit
```

I tried downloading letters, I logged in successfully.. and when click "load Penpals", the app crashed..
I checked the logs and noticed this error.

**Comment by MVMolodov** [comment]
Same. I have chrome installed, but the program crashes on loading penpals step
